test =  open("dummy.txt")
print("===> ",test.readline())
print("===> ",test.readline())
print("===> ",test.readline())
print("===> ",test.readline())
print("===> ",test.readline())
print("===> ",test.readline())
print("===> ",test.readline())
test.close()